#!/bin/bash
clear
echo "America/Sao_Paulo" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
dpkg-reconfigure --frontend noninteractive tzdata
rm *.sh > /dev/null 2>&1
wget https://raw.githubusercontent.com/juniorfdtech/painel12/master/criarusuario.sh > /dev/null 2>&1
wget https://raw.githubusercontent.com/juniorfdtech/painel12/master/remover.sh > /dev/null 2>&1
wget https://raw.githubusercontent.com/juniorfdtech/painel12/master/AlterarSenha.sh > /dev/null 2>&1
wget https://raw.githubusercontent.com/juniorfdtech/painel12/master/AlterarData.sh > /dev/null 2>&1
wget https://raw.githubusercontent.com/juniorfdtech/painel12/master/KillUser.sh > /dev/null 2>&1
wget https://raw.githubusercontent.com/juniorfdtech/painel12/master/sshmonitor.sh > /dev/null 2>&1
wget https://raw.githubusercontent.com/juniorfdtech/painel12/master/alterarlimite.sh > /dev/null 2>&1
wget https://raw.githubusercontent.com/juniorfdtech/painel12/master/backup.sh > /dev/null 2>&1
touch /root/usuarios.db > /dev/null 2>&1
chmod 777 *sh
service ssh restart
echo -e "\n\033[1;32mCONCLUIDO!\033[0m"
sleep 1
cat /dev/null > ~/.bash_history && history -c && clear
echo -e "\033[1;36mENTRE NO PAINEL E CRIE UMA CONTA SSH PRA VER SE ESTA TUDO OK!\033[0m"
rm inst
