#!/bin/bash
clear
echo "America/Sao_Paulo" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
dpkg-reconfigure --frontend noninteractive tzdata
rm *.sh > /dev/null 2>&1
link='raw.githubusercontent.com/juniorfdtech/painel12/master'
wget $link/criarusuario.sh > /dev/null 2>&1
wget $link/remover.sh > /dev/null 2>&1
wget $link/AlterarSenha.sh > /dev/null 2>&1
wget $link/AlterarData.sh > /dev/null 2>&1
wget $link/KillUser.sh > /dev/null 2>&1
wget $link/sshmonitor.sh > /dev/null 2>&1
wget $link/alterarlimite.sh > /dev/null 2>&1
touch /root/usuarios.db > /dev/null 2>&1
chmod 777 *sh
service ssh restart
echo -e "\n\033[1;32mCONCLUIDO!\033[0m"
sleep 2
cat /dev/null > ~/.bash_history && history -c && clear
echo -e "\033[1;36mENTRE NO PAINEL E CRIE UMA CONTA SSH PRA VER SE ESTA TUDO OK!\033[0m"
rm instt
