#!/bin/bash
apt update > /dev/null 2>&1
apt dist-upgrade -y > /dev/null 2>&1
echo "America/Sao_Paulo" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime > /dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1
sleep 1
echo -e "\033[1;32mINSTALANDO PAINEL"
echo ""
echo -ne "\033[1;33mDIGITE SUA SENHA ROOT\033[1;37m: "; read senha
echo -e "\033[1;32mOK\033[1;37m"
echo ""
echo -e "\033[1;32mAGUARDE..."
echo ""
apt-get install apache2 -y > /dev/null 2>&1
apt-get install cron curl unzip dirmngr apt-transport-https -y > /dev/null 2>&1
add-apt-repository ppa:ondrej/php -y > /dev/null 2>&1
apt-get update > /dev/null 2>&1
apt-get install php7.4 libapache2-mod-php7.4 php7.4-xml php7.4-mcrypt php7.4-mysql php7.4-mbstring php7.4-curl libssh2-1-dev php7.4-ssh2 -y > /dev/null 2>&1
phpenmod mcrypt
service apache2 restart > /dev/null 2>&1
sleep 1
wget http://repo.mysql.com/mysql-apt-config_0.8.15-1_all.deb > /dev/null 2>&1
echo "mysql-apt-config mysql-apt-config/select-server select mysql-5.7" | debconf-set-selections
DEBIAN_FRONTEND=noninteractive dpkg -i mysql-apt-config_0.8.15-1_all.deb > /dev/null 2>&1
rm -f mysql-apt-config_0.8.15-1_all.deb > /dev/null 2>&1
apt-get update > /dev/null 2>&1
echo "mysql-community-server mysql-community-server/root-pass password $senha" | debconf-set-selections
echo "mysql-community-server mysql-community-server/re-root-pass password $senha" | debconf-set-selections
echo "mysql-server mysql-server/root_password password $senha" | debconf-set-selections
echo "mysql-server mysql-server/root_password_again password $senha" | debconf-set-selections
echo "debconf mysql-server/root_password password $senha" | debconf-set-selections
echo "debconf mysql-server/root_password_again password $senha" | debconf-set-selections
apt-get install mysql-server -y > /dev/null 2>&1
echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections
echo "phpmyadmin phpmyadmin/app-password-confirm password $senha" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/admin-pass password $senha" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/app-pass password $senha" | debconf-set-selections
echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections
echo '[mysqld]
max_connections = 900' >> /etc/mysql/my.cnf
apt-get install phpmyadmin -y > /dev/null 2>&1
ln -s /usr/share/phpmyadmin /var/www/html/phpmyadmin
php -m | grep ssh2 > /dev/null 2>
cd /var/www/html
wget https://www.dropbox.com/s/qyhpecir4w4ui6f/internet4g.zip > /dev/null 2>&1
sleep 1
unzip -o internet4g.zip > /dev/null 2>&1
rm -rf internet4g.zip index.html > /dev/null 2>&1
sleep 1
mysql -h localhost -u root -p$senha -e "CREATE DATABASE internet4g" > /dev/null 2>&1
echo -e "\033[1;32mFINALIZANDO INSTALAÇÃO...\033[0m"
echo ""
sleep 1
echo -e "\033[1;32mESCOLHA OS DADOS DA REVENDA:"
echo -ne "\033[1;33m"
read -p "Nome do Admin: " nome
read -p "Senha: " senhadm
echo -ne "\033[0m"
sed -i "s;senhaDB;$senha;g" conexao.php > /dev/null 2>&1
sed -i "s;nomeadm;$nome;g" internet4g.sql > /dev/null 2>&1
sed -i "s;senhaadm;$senhadm;g" internet4g.sql > /dev/null 2>&1
mysql -h localhost -u root -p$senha internet4g < internet4g.sql > /dev/null 2>&1
rm -rf /root/internet4g.sql > /dev/null 2>&1
find /var/www/html/ -type f -exec chmod 664 {} +
find /var/www/html/ -type d -exec chmod 775 {} +
chmod 777 /var/www/html/download
service apache2 restart > /dev/null 2>&1
sleep 1
cd
clear
IP=$(wget -qO- ipv4.icanhazip.com)
echo ""
echo -e "\033[1;32m  PAINEL INSTALADO\033[0m"
echo ""
echo -e "\033[1;33m  Link de Acesso:\033[1;37m http://$IP/login.php\033[0m"
echo -e "\033[1;33m  Usuario:\033[1;37m admin\033[0m"
echo -e "\033[1;33m  Senha:\033[1;37m ${senhadm}\033[0m"
echo ""
echo -e "\033[1;32m  BOAS VENDAS!\033[0m"
rm -rf internet4g.sh > /dev/null 2>&1
cat /dev/null > ~/.bash_history && history -c
